    apiVersion: cert-manager.io/v1
     
    kind: Certificate
    metadata:
      name: k8s-itreers-pro-tls
    spec:
      secretName: k8s-itreers-pro
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
      commonName: k8s.itreers.pro
      dnsNames:
        - k8s.itreers.pro
