name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t itreers/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true itreers/react-test npm test

      - name: Set Service Key
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: onyx-osprey-456314-v2

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: multi-cluster
          location: europe-west1-c

      - name: Build
        run: |-
          docker build -t itreers/multi-client-k8s-gh:latest -t itreers/multi-client-k8s-gh:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t itreers/multi-server-k8s-gh:latest -t itreers/multi-server-k8s-gh:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t itreers/multi-worker-k8s-gh:latest -t itreers/multi-worker-k8s-gh:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push itreers/multi-client-k8s-gh:latest
          docker push itreers/multi-server-k8s-gh:latest
          docker push itreers/multi-worker-k8s-gh:latest

          docker push itreers/multi-client-k8s-gh:${{ env.SHA }}
          docker push itreers/multi-server-k8s-gh:${{ env.SHA }}
          docker push itreers/multi-worker-k8s-gh:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=itreers/multi-server-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=itreers/multi-client-k8s-gh:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=itreers/multi-worker-k8s-gh:${{ env.SHA }}
